spring.application.name=waterpark
spring.datasource.url=jdbc:mysql://localhost:3306/waterpark?characterEncoding=UTF-8&serverTimezone=Asia/Tokyo
spring.datasource.username=root
spring.datasource.password=
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp