# Generated by Django 4.2 on 2026-07-03 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('link_url', models.CharField(blank=True, max_length=255, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('sort_order', models.IntegerField()),
            ],
            options={
                'db_table': 'campaign_banners',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name_kana', models.CharField(max_length=255)),
                ('first_name_kana', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=7)),
                ('prefecture', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='Inquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'inquiries',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.delivery')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('hard', models.CharField(blank=True, max_length=255, null=True)),
                ('ken', models.CharField(blank=True, max_length=255, null=True)),
                ('kinds', models.CharField(blank=True, max_length=255, null=True)),
                ('base', models.CharField(blank=True, max_length=255, null=True)),
                ('is_recommended', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_or_color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('variant_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_main', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('litl', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.products')),
            ],
            options={
                'db_table': 'product_variants',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name_kana', models.CharField(max_length=255)),
                ('first_name_kana', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=7)),
                ('prefecture', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='StockHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('processed_at', models.DateTimeField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.orders')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.productvariants')),
            ],
            options={
                'db_table': 'stock_histories',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.products')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.users'),
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sum_price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.orders')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.productvariants')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
    ]
